### ISSUE TITLE
Use a built-in Chromium instead of WebView2

### ISSUE THREAD

**Issue by Zero3K** [SagalVanderklok/ChatRoomRecorder#18]
It would be nice if you had it use a built-in Chromium instead of WebView2.

**Comment by SagalVanderklok** [comment]
Puppeteer was used in the very first versions, but there were problems with interacting with websites using headless mode, so I had to switch to WebView2 in order to add the web browser tab in the application and save users from the need to perform antibot checks in a separate application

**Comment by Zero3K** [comment]
TubeDigger uses Chromium.

**Comment by SagalVanderklok** [comment]
What advantages could that bring? It looks like WebView2 does the job quite well

**Comment by Zero3K** [comment]
not having to install a separate program.

**Comment by SagalVanderklok** [comment]
I plan to build MSI packages with every release which will install WebView2 runtime. It will be easier that rework the whole application

**Comment by Zero3K** [comment]
I think the WebView2 runtime should be included with the program instead of having to have it be separately installed.

**Comment by SagalVanderklok** [comment]
Yeah, that's exactly what's planned

**Comment by Zero3K** [comment]
I think that it would be better to download a portable version when it is first ran.

**Comment by Zero3K** [comment]
When will this be done?

**Comment by SagalVanderklok** [comment]
The next step is to organize application settings as a list, add default preferred resolution and action settings, show extended messages about errors and implement simultaneous chat rooms updating. After that I'm gonna work on an installer

**Comment by Zero3K** [comment]
Okay.
