### ISSUE TITLE
Include FFmpeg with the next release

### ISSUE THREAD

**Issue by Zero3K** [SagalVanderklok/ChatRoomRecorder#20]
It would be nice if you did that so people don't have to manually download it and configure the program to use it.

**Comment by zxczxc322** [comment]
its just qol thing i personally have no problem with manually setting up ffmpeg
better add ability to select refreshing speed
error status indication(coz its happen sometimes without reason)
and then add support other camsites 
and in general this tool will be 100 times better than moniturbate

**Comment by SagalVanderklok** [comment]
> It would be nice if you did that so people don't have to manually download it and configure the program to use it.

I need to check that distributing the application with the ffmpeg binary doesn't violate any license agreements

**Comment by SagalVanderklok** [comment]
> its just qol thing i personally have no problem with manually setting up ffmpeg better add ability to select refreshing speed error status indication(coz its happen sometimes without reason) and then add support other camsites for me in general this tool will be 100 times better than moniturbate

Implementing of all these features are planned, but it may require some time. The next release will contain bug fixes and some GUI improvements. After that I'm planning to add detailed info about errors occured and setting for configuring room updates

**Comment by Zero3K** [comment]
I have found one that can be used and is smaller in file size. It is v3.2.2 and can be found at https://www.videohelp.com/software/ffmpeg/old-versions.

**Comment by Zero3K** [comment]
I think that it would be better to download FFmpeg when it is first ran.

**Comment by SagalVanderklok** [comment]
> I think that it would be better to download FFmpeg when it is first ran.

Yeah, I agree, The best option is to include ffmpeg into an MSI package, but if it's not possible due to legal restrictions downloading ffmpeg before the application starts is another option

**Comment by Zero3K** [comment]
Its license is GPL.

**Comment by SagalVanderklok** [comment]
While it's distributed under GPL it could include some non-free components (as described [here](https://www.ffmpeg.org/legal.html)) and it matters how the binary was build

**Comment by Zero3K** [comment]
Okay.
