### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Zero3K** [SagalVanderklok/ChatRoomRecorder#22]
1. Include the ability to minimize itself to the system tray when minimized and closed.
2. "Web browser" should be "Web Browser".
3. "Chat rooms" should be "Chat Rooms".
4. "Output directory" should be "Output Directory".
5. "FFmpeg path" should be "FFmpeg Path".
6. The address bar should automatically update itself with the new URL when clicking a link/one of the navigation buttons.

**Comment by SagalVanderklok** [comment]
Thanks! I'll take this into account when working on future releases

**Comment by Zero3K** [comment]
Any news regarding this?

**Comment by SagalVanderklok** [comment]
The build-in browser behavior has been improved. The remaining items are not in the implementation plans yet

**Comment by Zero3K** [comment]
Okay.
